services:
  - type: web
    name: resello-backend
    runtime: node
    plan: free
    rootDir: Backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
